// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"coffee-shop-api/internal/handler"
	"coffee-shop-api/internal/repository"
	"coffee-shop-api/internal/service"
)

// Injectors from wire.go:

// InitializeAPI creates a new API instance with all dependencies wired
func InitializeAPI() (*handler.CoffeeHandler, error) {
	inMemoryCoffeeRepository := repository.NewInMemoryCoffeeRepository()
	coffeeService := service.NewCoffeeService(inMemoryCoffeeRepository)
	coffeeHandler := handler.NewCoffeeHandler(coffeeService)
	return coffeeHandler, nil
}
