// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"coffee-shop-api/internal/handler"
	"coffee-shop-api/internal/repository"
	"coffee-shop-api/internal/service"
)

// Injectors from wire.go:

func InitializeAPI() (*handler.CoffeeHandler, error) {
	string2 := provideDBPath()
	sqLiteCoffeeRepository, err := repository.NewSQLiteCoffeeRepository(string2)
	if err != nil {
		return nil, err
	}
	coffeeService := service.NewCoffeeService(sqLiteCoffeeRepository)
	coffeeHandler := handler.NewCoffeeHandler(coffeeService)
	return coffeeHandler, nil
}
